services:
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.test
    restart: unless-stopped
    volumes:
      - ./backend:/var/www:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - ./docker/nginx/common:/etc/nginx/conf.d:ro
    networks:
      - slim-test
    ports:
      - "${NGINX_PORT:-80}:80"
      - "443:443"
    depends_on:
      php-fpm:
        condition: service_healthy

  php-fpm:
    user: root
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile.test
      target: development
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    env_file:
      - .env.backend.test
    networks:
      - slim-test
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    env_file:
      - .env.backend.test
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'sail'
      MYSQL_PASSWORD: 'password'
    volumes:
      - 'mysql-data-production:/var/lib/mysql'
    networks:
      - slim-test
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-ppassword'
      retries: 3
      timeout: 5s

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - slim-test
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  slim-test:

volumes:
  mysql-data-production:
